### ISSUE TITLE
The styling of the card does not look at all like the documentation

### ISSUE THREAD

**Issue by KennethLavrsen** [DarkFox/rejseplanen-stog-card#1]
Hi

I just installed this new card.

I used HACS to install it so it is almost impossible to do it wrong

The result is 

![image](https://user-images.githubusercontent.com/8373419/93689223-a4993d80-facc-11ea-8782-bd2c2058bdfd.png)

It is the same as the other bug I raised on the rejseplanen-card

I notice that your documentation does not at all match how HACS installs things

You write that you put this in the lovelace resources

/community_plugin/rejseplanen-stog-card/rejseplanen-stog-card.js

But in reality HACS installs it as

/hacsfiles/rejseplanen-stog-card/rejseplanen-stog-card.js

It cannot be that the JS is not found because then the card would totally fail to work. It is just the styling that fails to work. But maybe you hardcoded something that depends on the exact paths to show in the documentation?

No matter what. It does not look good

**Comment by DarkFox** [comment]
Hmm, I think something's gone wrong in the HACS config, it's supposed to be added as `type: js`, not `module`. Changing that should fix it. I used some old template in the documentation and forgot to update it when copying it over, I'll fix that.

**Comment by DarkFox** [comment]
You should also try doing a forced reload of the page after updating, as the CSS styles have changed.

**Comment by KennethLavrsen** [comment]
You cannot add the resource as js anymore. It was deprecated. The HA user interface does not allow js anymore. You will have to change Lovelace to 100% yaml defined which is only for the most hard core geeks.

**Comment by KennethLavrsen** [comment]
I tried to hack the lovelace json file in .storage from module to js for both the normal card and stog card. I restarted HA and I manually reloaded the page in browsers of several computers. Even control F5. Still does not pick up the styling.

**Comment by KennethLavrsen** [comment]
The update to 1.0.2 did not fix this.
I did try on multiple browsers and both IOS, Windows and Linux. It all looks the same

**Comment by MSkeem** [comment]
Hi - have you guys found a solution for this? I just installed the card, and have the same issue as listed above.

**Comment by DarkFox** [comment]
@MSkeem The issue is the same as this: https://github.com/DarkFox/rejseplanen-card/issues/7#issuecomment-706279770
I'll have to rewrite the card to load as module to make it work.

**Comment by tpbillund** [comment]
@MSkeem Solution here...
https://github.com/DarkFox/rejseplanen-card/issues/7#issuecomment-716172853

**Comment by KennethLavrsen** [comment]
I have installed the new version and now it does not work at all

I get "custom element does not exist". Did you misspell something in the fix?  

The normal rejseplanen-card works now with the styling fix. But the stog variant is now broken

![image](https://user-images.githubusercontent.com/8373419/98484524-6d175980-2210-11eb-8c6e-2e78338df74a.png)

**Comment by KennethLavrsen** [comment]
Follow up
The stog card generates this error in the home assistant log

Log Details (ERROR)
Logger: frontend.js.latest.202010214
Source: components/system_log/__init__.py:193
First occurred: 22:27:02 (1 occurrences)
Last logged: 22:27:02

http://192.168.1.15:8123/hacsfiles/rejseplanen-card/rejseplanen-card.js:1:1 Uncaught SyntaxError: Identifier 'n' has already been declared

**Comment by DarkFox** [comment]
I'm not able to reproduce that issue. Which browser are you using?

**Comment by KennethLavrsen** [comment]
Google Chrome on Windows 10 and Safari on iPad IOS. Exact same problem. I uninstalled and reinstalled via HACS but still same problem.

**Comment by DurgNomis-drol** [comment]
I just tried installing it manually, because i run homeassistant in a docker container, and it works normally for me too. Can you try that and see if it solves the problem?

**Comment by KennethLavrsen** [comment]
The new update that came out today both removed the error in the log and both rejseplanen and rejseplanen-stog works fine now and look very good. Thanks for the fixes

**Comment by DarkFox** [comment]
Thanks for everyone's help (and gentle push) to get this fixed. 👍
